services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: public_user
      POSTGRES_PASSWORD: publicN3xt!
      POSTGRES_DB: public_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
